// Generated by scripts/build-interaction-examples.py. Edit the guides, not this file.
export const InteractionExamples = () => ({
  "card": {
    "message": {
      "parts": [
        {
          "type": "text",
          "value": "This one fits."
        },
        {
          "type": "rich_card",
          "media": {
            "type": "image",
            "url": "https://example.com/lagoon-house.jpg",
            "height": "medium"
          },
          "title": "Lagoon House, Railay",
          "description": "Pool villa, 4 min to the beach. $212 a night.",
          "suggestions": [
            {
              "type": "reply",
              "label": "Book",
              "id": "book_lagoon"
            },
            {
              "type": "open_url",
              "label": "Details",
              "url": "https://example.com/lagoon-house"
            }
          ]
        }
      ],
      "idempotency_key": "krabi-card-001"
    }
  },
  "carousel": {
    "message": {
      "parts": [
        {
          "type": "text",
          "value": "Three that fit. Swipe to compare."
        },
        {
          "type": "carousel",
          "card_width": "medium",
          "cards": [
            {
              "media": {
                "type": "image",
                "url": "https://example.com/lagoon-house.jpg"
              },
              "title": "Lagoon House",
              "description": "$212 a night",
              "suggestions": [
                {
                  "type": "reply",
                  "label": "Book",
                  "id": "book_lagoon"
                }
              ]
            },
            {
              "media": {
                "type": "image",
                "url": "https://example.com/cliffside.jpg"
              },
              "title": "Cliffside Villas",
              "description": "$238 a night",
              "suggestions": [
                {
                  "type": "reply",
                  "label": "Book",
                  "id": "book_cliffside"
                }
              ]
            }
          ]
        },
        {
          "type": "buttons",
          "items": [
            {
              "label": "Cheaper"
            },
            {
              "label": "Closer to the beach"
            }
          ]
        }
      ]
    }
  },
  "form": {
    "message": {
      "parts": [
        {
          "type": "text",
          "value": "Please share your visit preferences."
        },
        {
          "type": "form",
          "title": "Your visit",
          "show_summary": true,
          "splash": {
            "title": "Plan your visit",
            "text": "Share a few details before you arrive.",
            "button_title": "Continue"
          },
          "received_message": {
            "title": "Visit details",
            "subtitle": "Complete two pages"
          },
          "reply_message": {
            "title": "Form sent",
            "subtitle": "Tap to review your answers"
          },
          "pages": [
            {
              "id": "about",
              "title": "About you",
              "fields": [
                {
                  "id": "name",
                  "type": "text",
                  "label": "Name",
                  "placeholder": "Your name",
                  "required": true
                },
                {
                  "id": "meal",
                  "type": "select",
                  "label": "Meal",
                  "required": true,
                  "options": [
                    {
                      "value": "veg",
                      "label": "Vegetarian"
                    },
                    {
                      "value": "fish",
                      "label": "Fish"
                    }
                  ]
                },
                {
                  "id": "extras",
                  "type": "select",
                  "label": "Extras",
                  "multiple": true,
                  "options": [
                    {
                      "value": "tea",
                      "label": "Tea"
                    },
                    {
                      "value": "cake",
                      "label": "Cake"
                    }
                  ]
                }
              ]
            },
            {
              "id": "visit",
              "title": "Visit preferences",
              "fields": [
                {
                  "id": "region",
                  "type": "picker",
                  "label": "Region",
                  "options": [
                    {
                      "value": "east",
                      "label": "East"
                    },
                    {
                      "value": "west",
                      "label": "West"
                    }
                  ]
                },
                {
                  "id": "date",
                  "type": "date",
                  "label": "Visit date",
                  "required": true,
                  "min_date": "2026-10-01",
                  "max_date": "2026-12-31"
                },
                {
                  "id": "notes",
                  "type": "text",
                  "label": "Notes",
                  "multiline": true,
                  "max_length": 500
                },
                {
                  "id": "updates",
                  "type": "select",
                  "label": "Visit updates",
                  "multiple": true,
                  "options": [
                    {
                      "value": "yes",
                      "label": "Send me visit updates"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ],
      "idempotency_key": "visit-form-001"
    }
  }
});
