#!/usr/bin/env python3
"""Keep the live examples byte-for-value equal to the guide's wire examples."""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
cards = (ROOT / "interactions/rich-cards.mdx").read_text()
requests = [json.loads(block) for block in re.findall(r"^```json[^\n]*\n(.*?)^```", cards, re.M | re.S)]
form = (ROOT / "interactions/form.mdx").read_text()
visit = json.JSONDecoder().raw_decode(form.split("const request = ", 1)[1])[0]
examples = {"card": requests[0], "carousel": requests[1], "form": visit}
output = "// Generated by scripts/build-interaction-examples.py. Edit the guides, not this file.\n"
output += "export const InteractionExamples = () => (" + json.dumps(examples, ensure_ascii=False, indent=2) + ");\n"
target = ROOT / "snippets/interaction-examples.jsx"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != output:
        sys.exit("Live interaction examples are stale; run python3 scripts/build-interaction-examples.py")
else:
    target.write_text(output)
